name: CI
on: [push, issue_comment]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cat docker_tag dir
        run: |
          pwd
          ls ./docker_tag

      - name: Setup Composer
        uses: https://github.com/php-actions/composer@v6
        # with:
        #   php_version: ${{ matrix.php-version }}

      - run: echo "Composer dependencies have been installed"

      - run: vendor/bin/phpunit
