name: CI
on: [push, issue_comment]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cat docker_tag
        run: |
          pwd
          echo '${{ github.action_path }}'
          ls -l
          cat ${{ github.action_path }}/docker_tag
      - name: Setup Composer
        uses: php-actions/composer@v6
        with:
          php_version: "7.2"

      - run: echo "Composer dependencies have been installed"

      - run: vendor/bin/phpunit
